apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader
  namespace: default
rules:
- apiGroups: [""] # "" indicated all the core API groups
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
