apiVersion: v1
kind: Service
metadata:
  name: node-agent-metrics-local-service
  namespace: power-manager
spec:
  selector:
    name: power-node-agent-pod
  ports:
    - protocol: TCP
      port: 10001
      targetPort: metrics
  internalTrafficPolicy: Local
