apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: metrics-reader
  labels:
    app.kubernetes.io/name: kubernetes-power-manager
    app.kubernetes.io/managed-by: kustomize
rules:
  - nonResourceURLs: [ "/metrics" ]
    verbs: [ "get" ]
