# permissions for end users to edit cpuperformancescalingprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: intel-kubernetes-power-manager
    app.kubernetes.io/managed-by: kustomize
  name: cpuperformancescalingprofile-editor-role
rules:
- apiGroups:
  - power.intel.com
  resources:
  - cpuperformancescalingprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - power.intel.com
  resources:
  - cpuperformancescalingprofiles/status
  verbs:
  - get
