# permissions for end users to view cpuscalingconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: intel-kubernetes-power-manager
    app.kubernetes.io/managed-by: kustomize
  name: cpuscalingconfiguration-viewer-role
rules:
- apiGroups:
  - power.amdepyc.com
  resources:
  - cpuscalingconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - power.amdepyc.com
  resources:
  - cpuscalingconfigurations/status
  verbs:
  - get
