# permissions for end users to edit cpuscalingprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: intel-kubernetes-power-manager
    app.kubernetes.io/managed-by: kustomize
  name: cpuscalingprofile-editor-role
rules:
- apiGroups:
  - power.amdepyc.com
  resources:
  - cpuscalingprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - power.amdepyc.com
  resources:
  - cpuscalingprofiles/status
  verbs:
  - get
