# permissions for end users to view cpuscalingprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubernetes-power-manager
    app.kubernetes.io/managed-by: kustomize
  name: cpuscalingprofile-viewer-role
rules:
- apiGroups:
  - power.amdepyc.com
  resources:
  - cpuscalingprofiles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - power.amdepyc.com
  resources:
  - cpuscalingprofiles/status
  verbs:
  - get
