# permissions for end users to view cstates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cstates-viewer-role
rules:
  - apiGroups:
      - power.amdepyc.com
    resources:
      - cstates
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - power.amdepyc.com
    resources:
      - cstates/status
    verbs:
      - get
