# permissions for end users to view powerconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: powerconfig-viewer-role
rules:
- apiGroups:
  - power.intel.com
  resources:
  - powerconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - power.intel.com
  resources:
  - powerconfigs/status
  verbs:
  - get
