# permissions for end users to view powernodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: powernode-viewer-role
rules:
- apiGroups:
  - power.intel.com
  resources:
  - powernodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - power.intel.com
  resources:
  - powernodes/status
  verbs:
  - get
