# permissions for end users to edit powerconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: powerconfig-editor-role
rules:
- apiGroups:
  - power.intel.com
  resources:
  - powerconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - power.intel.com
  resources:
  - powerconfigs/status
  verbs:
  - get
