# permissions for end users to edit powernodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: powernode-editor-role
rules:
- apiGroups:
  - power.intel.com
  resources:
  - powernodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - power.intel.com
  resources:
  - powernodes/status
  verbs:
  - get
