# permissions for end users to view powerpods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: powerpod-viewer-role
rules:
- apiGroups:
  - power.intel.com
  resources:
  - powerpods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - power.intel.com
  resources:
  - powerpods/status
  verbs:
  - get
