# permissions for end users to edit profiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: profile-editor-role
rules:
- apiGroups:
  - power.intel.com
  resources:
  - profiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - power.intel.com
  resources:
  - profiles/status
  verbs:
  - get
