apiVersion: v1
kind: ServiceAccount
metadata:
  name: intel-power-operator
  namespace: intel-power

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: intel-power-node-agent
  namespace:  intel-power

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  name: operator-custom-resource-definitions-role
  namespace: intel-power
rules:
- apiGroups: ["", "power.intel.com", "apps"]
  resources: ["powerconfigs", "powerconfigs/status", "powerprofiles", "powerprofiles/status", "events", "daemonsets"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operator-custom-resource-definitions-role-binding
  namespace: intel-power
subjects:
- kind: ServiceAccount
  name: intel-power-operator
  namespace: intel-power
roleRef:
  kind: Role
  name: operator-custom-resource-definitions-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-nodes
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/status"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-nodes-binding
subjects:
- kind: ServiceAccount
  name: intel-power-operator
  namespace: intel-power
roleRef:
  kind: ClusterRole
  name: operator-nodes
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-agent-cluster-resources
rules:
- apiGroups: ["", "power.intel.com"]
  resources: ["nodes", "nodes/status", "pods", "pods/status", "powerprofiles", "powerprofiles/status", "powerworkloads", "powerworkloads/status", "powernodes", "powernodes/status"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-agent-cluster-resources-binding
subjects:
- kind: ServiceAccount
  name: intel-power-node-agent
  namespace: intel-power
roleRef:
  kind: ClusterRole
  name: node-agent-cluster-resources
  apiGroup: rbac.authorization.k8s.io

---
