apiVersion: v1
kind: ServiceAccount
metadata:
  name: intel-power-operator
  namespace: intel-power

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: intel-power-operator
  namespace: intel-power
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "apps"
  resources:
  - deployments
  - daemonsets
  verbs:
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: intel-power-operator
  namespace: intel-power
subjects:
- kind: ServiceAccount
  name: intel-power-operator
roleRef:
  kind: Role
  name: intel-power-operator
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: intel-power-operator
rules:
- apiGroups: [""]
  resources: ["nodes", "events"]
  verbs: ["get", "list", "watch", "patch", "update"]
- apiGroups: [""]
  resources: ["nodes/status"] 
  verbs: ["get", "list", "watch", "patch", "update"]
- apiGroups: [""]
  resources: ["pods", "configmaps"]
  verbs: ["get", "list", "watch", "patch", "create", "update"]
- apiGroups: ["power.intel.com"]
  resources: ["powerconfigs", "powerconfigs/status", "powernodes", "powernodes/status", "powerprofiles", "powerprofiles/status", "powerworkloads", "powerworkloads/status"] 
  verbs: ["get", "list", "watch", "patch", "create", "update"]
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get", "list", "watch", "patch", "create", "update"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: intel-power-operator
roleRef:
  kind: ClusterRole
  name: intel-power-operator 
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  namespace: intel-power 
  name: intel-power-operator
