
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - power.intel.com
  resources:
  - powerconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - power.intel.com
  resources:
  - powerconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - power.intel.com
  resources:
  - powernodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - power.intel.com
  resources:
  - powernodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - power.intel.com
  resources:
  - powerpods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - power.intel.com
  resources:
  - powerpods/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - power.intel.com
  resources:
  - powerprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - power.intel.com
  resources:
  - powerprofiles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - power.intel.com
  resources:
  - powerworkloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - power.intel.com
  resources:
  - powerworkloads/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs:
  - get
  - patch
  - update
  - list
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - update
