apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-manager
  namespace: system
  labels:
    app.kubernetes.io/name: intel-kubernetes-power-manager
    app.kubernetes.io/managed-by: kustomize
