# Default values for kubernetes-power-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Intel Power namespace
namespace:
  label: controller-manager
  name: power-manager

# Service Account for the overarching operator
operatorserviceaccount:
  name: power-operator
  namespace: power-manager

# Service Account for the Power Node Agent
agentserviceaccount:
  name: power-node-agent
  namespace: power-manager

# Role for the overarching operator
operatorrole:
  name: operator-custom-resource-definitions-role
  namespace: power-manager
  resources: ["powerconfigs", "powerconfigs/status", "powerprofiles", "powerprofiles/status", "events", "daemonsets", "configmaps", "configmaps/status", "leases", "uncores"]

# Role Binding for the overarching operator
operatorrolebinding:
  name: operator-custom-resource-definitions-role-binding
  namespace: power-manager
  serviceaccount:
    name: power-operator
    namespace: power-manager
  rolename: operator-custom-resource-definitions-role

# Cluster Role for the overarching operator
operatorclusterrole:
  name: operator-nodes
  resources: ["nodes", "nodes/status", "configmaps", "configmaps/status", "powerconfigs", "powerconfigs/status", "powerprofiles", "powerprofiles/status", "powerworkloads", "powerworkloads/status", "powernodes", "powernodes/status", "events", "daemonsets", "uncores", "cpuscalingprofiles", "cpuscalingprofiles/status", "cpuscalingconfigurations", "cpuscalingconfigurations/status"]

# Cluster Role Binding for the overarching operator
operatorclusterrolebinding:
  name: operator-nodes-binding
  serviceaccount:
    name: power-operator
    namespace: power-manager
  clusterrolename: operator-nodes

# Cluster Role for the Power Node Agent
agentclusterrole:
  name: node-agent-cluster-resources
  resources: ["nodes", "nodes/status", "pods", "pods/status", "cronjobs", "cronjobs/status", "powerprofiles", "powerprofiles/status", "powerworkloads", "powerworkloads/status", "powernodes", "powernodes/status", "cstates", "cstates/status", "timeofdays", "timeofdays/status", "timeofdaycronjobs", "timeofdaycronjobs/status", "uncores", "uncores/status", "cpuscalingprofiles", "cpuscalingprofiles/status", "cpuscalingconfigurations", "cpuscalingconfigurations/status"]

# Cluster Role Binding for the Power Node Agent
agentclusterrolebinding:
  name: node-agent-cluster-resources-binding
  serviceaccount:
    name: power-node-agent
    namespace: power-manager
  clusterrolename: node-agent-cluster-resources

# Deployment for the overarching operator
operator:
  name: controller-manager
  namespace: power-manager
  labels:
    controlplane: controller-manager
  replicas: 1
  container:
    serviceaccount:
      name: power-operator
    command: /manager
    args: --leader-elect
    image: amdepyc/power-operator:v1.1.0
    name: manager
    cpu:
      limits: 200m
      requests: 200m
    memory:
      limits: 100Mi
      requests: 100Mi

# Values for exposing metrics from node-agent locally
agentmetricsservice:
  name: node-agent-metrics-local-service
  namespace: power-manager
  selectorname: power-node-agent-pod
  port: 10001

# Values for the PowerConfig
powerconfig:
  name: power-config
  namespace: power-manager
  nodeselector:
    label: "feature.node.kubernetes.io/power-node"
    value: 'true'

# Values for the Shared PowerProfile
sharedprofile:
  name: shared
  namespace: power-manager
  spec:
    name: "shared"
    max:
    min:
    epp: "power"
    governor: "powersave"
