apiVersion: power.intel.com/v1
kind: CPUScalingProfile
metadata:
  labels:
    app.kubernetes.io/name: intel-kubernetes-power-manager
    app.kubernetes.io/managed-by: kustomize
  name: cpuscalingprofile-sample
spec:
  name: sample-profile
  samplePeriod: 10ms
  min: 2000
  max: 3000
  epp: "power"
