apiVersion: power.intel.com/v1
kind: Uncore
metadata:
  labels:
    app.kubernetes.io/name: Uncore
    app.kubernetes.io/instance: uncore-sample
    app.kubernetes.io/part-of: kubernetes-power-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubernetes-power-manager
  name: <NODE_NAME>
  namespace: intel-power
spec:
  sysMax: 2300000
  sysMin: 1300000
  dieSelector:
    - package: 0
      die: 0
      min: 1500000
      max: 2400000
