apiVersion: power.amdepyc.com/v1
kind: PowerProfile
metadata:
  name: shared
  namespace: power-manager
spec:
  name: "shared"
  max: 1000
  min: 1000
  epp: "power"
  shared: true
  governor: "powersave"
