name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22.3'

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: 'latest'
        args: '--timeout 5m'

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22.3'

    - name: Set up Operator SDK
      run: |
        curl -LO https://github.com/operator-framework/operator-sdk/releases/download/v1.37.0/operator-sdk_linux_amd64
        chmod +x operator-sdk_linux_amd64
        sudo mv operator-sdk_linux_amd64 /usr/local/bin/operator-sdk

    - name: Build
      run: |
        make build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image for power-operator
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./build/Dockerfile
        push: false    # Ensure push is false to avoid pushing the image
        tags: amd/power-operator:latest    # This can still be specified for test/verification purposes

    - name: Build Docker image for power-node-agent
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./build/Dockerfile.nodeagent
        push: false    # Ensure push is false to avoid pushing the image
        tags: amd/power-node-agent:latest    # This can still be specified for test/verification purposes

