name: Publish Docker Image

on:
  push:
    tags:
      - 'v*'  # This will match any tag that starts with "v"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push power-operator Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: build/Dockerfile
          push: true
          tags: ${{ vars.DOCKER_ORGANIZATION }}/${{ vars.DOCKER_REPO_POWER_OPERATOR }}:${{ env.VERSION }}

      - name: Build and push power-node-agent Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: build/Dockerfile.nodeagent
          push: true
          tags: ${{ vars.DOCKER_ORGANIZATION }}/${{ vars.DOCKER_REPO_NODE_AGENT }}:${{ env.VERSION }}

